debug: false
prepare: false

data_dir: "/home/pervinco/Datasets/leash-bio"
output_dir: "/home/pervinco/Datasets/leash-bio/preprocessed"
save_dir: "/home/pervinco/Models/leash-bio"
ckpt_dir: null

train_parquet: "/home/pervinco/Datasets/leash-bio/train.parquet"
test_parquet: "/home/pervinco/Datasets/leash-bio/test.parquet"

n_iter: 10
limit: 200000
radius: 2
vec_dim: 1024

num_boost: 300 ## 100
learning_rate: 0.01 ## 0.05
feature_frac: 1.0
num_leaves: 30 ## 31

predict_top_k: 10

target_proteins:
  - HSA
  - sEH
  - BRD4

uniprot_dicts:
  sEH: "P34913"
  BRD4: "O60885"
  HSA: "P02768"
